-- Set the database and schema
USE DATABASE VYTALIZE_0171;
USE SCHEMA VYTALIZE_0171.DEV_SCHEMA;

CREATE OR REPLACE TABLE CLMDTLS_TABLE ( 
    OMC_CLM_ID INTEGER, 
    OMC_CLM_DTLS_ID INTEGER, 
    LINE_NUM INTEGER, 
    INC_FROM STRING, 
    INC_TO STRING, 
    ICD_CD STRING, 
    OMC_ICD_RISK_NBR INTEGER, 
    CPT_CD STRING, 
    SUB_TYPE STRING, 
    CLMS_CHRG FLOAT, 
    PAID_AMT FLOAT 
);

COPY INTO CLMDTLS_TABLE (OMC_CLM_DTLS_ID, OMC_CLM_ID, LINE_NUM, 
INC_FROM, INC_TO, ICD_CD, OMC_ICD_RISK_NBR,CPT_CD, SUB_TYPE, CLMS_CHRG,
PAID_AMT)
FROM (
  SELECT t.$1, t.$2, t.$3, t.$9, t.$10, t.$14,t.$34, t.$19,t.$17, t.$22, t.$25
  FROM @VYTALIZE_0171_stage/claim_details.csv t
)
FILE_FORMAT = (
  TYPE = 'CSV'
  SKIP_HEADER = 1-- Skips the CSV header row
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
);


CREATE OR REPLACE TABLE CLMHDRS_TABLE (
    OMC_CLM_ID STRING,
    MBR_ID STRING
);

COPY INTO CLMHDRS_TABLE (OMC_CLM_ID, MBR_ID)
FROM (
  SELECT t.$1, t.$2
  FROM @VYTALIZE_0171_stage/claim_headers.csv t
)
FILE_FORMAT = (
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1 -- Skips the CSV header row
);

CREATE OR REPLACE TABLE PTDTLS_TABLE (
    MBR_ID STRING,
    LST_NAME STRING,
    FST_NAME STRING,
    MDL_NAME STRING,
    PT_GNDR STRING,
    PT_DOB STRING,
    PT_ST STRING,
    PT_ZIP STRING
);

COPY INTO PTDTLS_TABLE (MBR_ID, LST_NAME, FST_NAME, MDL_NAME, PT_GNDR, 
PT_DOB, PT_ST, PT_ZIP)
FROM (
  SELECT t.$5, t.$4, t.$2, t.$3, t.$7, t.$8, t.$10, t.$11 
  FROM @VYTALIZE_0171_stage/patient_mstr.csv t
)
FILE_FORMAT = (
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1 -- Skips the CSV header row
);



