-- Setup script for Vytalize development environment
-- Co-authored with CoCo
USE ROLE ACCOUNTADMIN;

-- Roles
CREATE OR REPLACE ROLE DEVELOPER_ROLE;
GRANT ROLE DEVELOPER_ROLE TO ROLE SYSADMIN;
BEGIN
  LET user_name := CURRENT_USER();
  GRANT ROLE DEVELOPER_ROLE TO USER IDENTIFIER(:user_name);
END;

GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE DEVELOPER_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DEVELOPER_ROLE;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE DEVELOPER_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE DEVELOPER_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE DEVELOPER_ROLE;
--GRANT USAGE ON INTEGRATION GITHUB_API_INTEGRATION TO ROLE DEVELOPER_ROLE;

-- Databases

CREATE OR REPLACE DATABASE VYTALIZE_0171;
CREATE OR REPLACE SCHEMA VYTALIZE_0171.DEV_SCHEMA;
CREATE OR REPLACE SCHEMA VYTALIZE_0171.PROD_SCHEMA;
CREATE OR REPLACE SCHEMA VYTALIZE_0171.ML_MODELS;